{
  return convertExceptionToValue(async.pathExists(container),ContainerNotFoundException.class,false);
}
