{
  try {
    value=task.call();
  }
 catch (  InterruptedException e) {
    interruptedException=e;
  }
catch (  Exception e) {
    executionException=new ExecutionException(e);
  }
 finally {
    ran=true;
  }
}
