{
  try {
    return future.get();
  }
 catch (  Exception e) {
    return attemptConvert(e);
  }
}
