{
  try {
    return answers.get(input).call();
  }
 catch (  Exception e) {
    throw propagate(e);
  }
}
