{
  fn.handleError(command,retryAfterTrumps);
  assertEquals(command.getException().getClass(),RetryAfterException.class);
  assertEquals(command.getException().getMessage(),"retry in 54 seconds");
}
