{
  Function<String,String> delegate=createMock(Function.class);
  AuthorizationException auth=createMock(AuthorizationException.class);
  RuntimeException throwable=new RuntimeException(auth);
  expect(delegate.apply("baz")).andThrow(throwable);
  expect(auth.getCause()).andReturn(null).anyTimes();
  replay(delegate);
  replay(auth);
  RetryOnTimeOutExceptionFunction<String,String> supplier=new RetryOnTimeOutExceptionFunction<String,String>(delegate);
  try {
    supplier.apply("baz");
    fail();
  }
 catch (  RuntimeException e) {
    assertEquals(e.getCause(),auth);
  }
  verify(delegate);
  verify(auth);
}
