{
  Throwable exception=find(getCausalChain(from),hasResponse(from),null);
  if (exception != null) {
    HttpResponseException responseException=(HttpResponseException)exception;
    HttpResponse response=responseException.getResponse();
    if (response != null && response.getStatusCode() == Status.SEE_OTHER.getStatusCode()) {
      return immediateFuture(null);
    }
  }
  throw propagate(from);
}
