{
  Exception e=getErrorWithCode("blah");
  new ReturnTrueIfBucketAlreadyOwnedByYou().apply(e);
}
