{
  Exception e=getErrorWithCode("blah");
  new ReturnFalseIfBucketAlreadyOwnedByYou().apply(e);
}
